title       = The Great Wall
name        = the_great_wall
description = Defense game: hold the wall against 200 waves of border-crossers. Play as Trump, kill or capture, build economy, save the cozy house.
author      = guillaume34110
min_minetest_version = 5.8
disallowed_mapgens = v6
textdomain  = game_description
